export const SET_EXPOSITION = 'SET_EXPOSITION'
export const ADD_EXPOSITION = 'ADD_EXPOSITION'
export const UPDATE_EXPOSITION = 'UPDATE_EXPOSITION' 
export const DELETE_EXPOSITION = 'DELETE_EXPOSITION' 
export const SET_EXHIBIT_IN_EXPOSITION = 'SET_EXHIBIT_IN_EXPOSITION'

export const SET_EXHIBIT = 'SET_EXHIBIT'
export const GET_EXHIBIT_NOT_IN_EXPOSITION = 'GET_EXHIBIT_NOT_IN_EXPOSITION'
export const RESET_STORE_EXHIBIT = 'RESET_STORE_EXHIBIT'

export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDE_LOADER = 'HIDE_LOADER'
